#!/opt/homebrew/bin/bash
# Kill pane and redistribute remaining panes proportionally

# Predefined ratios by column count (same as smart-split)
declare -A RATIOS
RATIOS[1]="100"
RATIOS[2]="60 40"
RATIOS[3]="50 30 20"
RATIOS[4]="40 25 20 15"
RATIOS[5]="35 22 18 14 11"

# Kill all child processes of current pane, then kill the pane
pid=$(tmux display-message -p '#{pane_pid}')
pkill -TERM -P "$pid" 2>/dev/null
sleep 0.1
pkill -KILL -P "$pid" 2>/dev/null
tmux kill-pane

# Small delay to let tmux update layout
sleep 0.05

# Count remaining columns
cols=$(tmux list-panes -F '#{pane_left}' 2>/dev/null | sort -u | wc -l | tr -d ' ')

# Only redistribute if we have panes left and a ratio for this count
[[ "$cols" -lt 1 ]] && exit 0
ratio="${RATIOS[$cols]}"
[[ -z "$ratio" ]] && exit 0

# Get one pane per column (sorted left to right)
mapfile -t panes < <(tmux list-panes -F '#{pane_left} #{pane_id}' | sort -n -k1 | awk '!seen[$1]++ {print $2}')
read -ra widths <<< "$ratio"

# Resize each column
for i in "${!panes[@]}"; do
    if [[ $i -lt ${#widths[@]} ]]; then
        tmux resize-pane -t "${panes[$i]}" -x "${widths[$i]}%"
    fi
done
