#!/bin/bash
# Fetch secrets from private GitHub repo and write to ~/.zshrc.local
# Requires: gh auth login (GitHub CLI authenticated)

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

info() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }

SECRETS_REPO="A-PachecoT/dotfiles-secrets"
SECRETS_FILE="secrets.json"
OUTPUT="$HOME/.zshrc.local"

# Check gh auth
if ! gh auth status &>/dev/null; then
    error "Not authenticated with GitHub CLI"
    info "Run: gh auth login"
    exit 1
fi

# Check if private repo is accessible
if ! gh repo view "$SECRETS_REPO" &>/dev/null; then
    error "Cannot access $SECRETS_REPO"
    info "Create it: gh repo create dotfiles-secrets --private"
    info "Then add secrets.json with your API keys:"
    info '  {"NAMECHEAP_API_USER":"...","NAMECHEAP_API_KEY":"...","WHATSAPP_TOKEN":"...","CF_PURGE_TOKEN":"..."}'
    exit 1
fi

info "Fetching secrets from $SECRETS_REPO..."

# Fetch and decode secrets.json from private repo
RAW=$(gh api "repos/$SECRETS_REPO/contents/$SECRETS_FILE" --jq '.content' 2>/dev/null)
if [[ -z "$RAW" ]]; then
    error "Failed to fetch $SECRETS_FILE from $SECRETS_REPO"
    exit 1
fi

# Decode base64 and generate .zshrc.local
DECODED=$(echo "$RAW" | base64 --decode)

# Write header
cat > "$OUTPUT" << 'HEADER'
# Machine-local secrets (auto-generated by setup/secrets-setup.sh)
# DO NOT commit this file. Managed via: gh repo A-PachecoT/dotfiles-secrets
HEADER

# Parse JSON and write export statements
echo "$DECODED" | python3 -c "
import json, sys
data = json.load(sys.stdin)
for key, value in data.items():
    print(f'export {key}=\"{value}\"')
" >> "$OUTPUT"

chmod 600 "$OUTPUT"
success "Secrets written to $OUTPUT ($(echo "$DECODED" | python3 -c "import json,sys; print(len(json.load(sys.stdin)))" ) keys)"
