name: Sync Dotfiles

on:
  push:
    branches: [ main ]
    paths:
      - '.zshrc'
      - '.gitconfig'
  schedule:
    - cron: '0 0 * * 0'  # Weekly sync on Sunday midnight
  workflow_dispatch:  # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      FILES_TO_SYNC: ".zshrc .gitconfig"

    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa      # Write the private key to the file
          chmod 600 ~/.ssh/id_rsa                      # Set the correct permissions for the private key
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts     # Write the known hosts to the file

      - name: Sync dotfiles
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        run: |
          for file in $FILES_TO_SYNC; do                         # Iterate over the files
            if [ -f "$file" ]; then                              # Check if the file exists
              echo "Syncing $file..."                            # Print the file name
              scp "$file" "$REMOTE_USER@$REMOTE_HOST:~/$file"    # Sync the file to the remote host
            fi
          done
